/**
 * Seed Data - 전 세계 주요 여행지 100개+
 * 하이브리드 모드: 로컬 DB 큐레이션 데이터
 */

const destinationsData = [
  // ========================================
  // 유럽 (30개)
  // ========================================
  {
    id: 'turkey-istanbul',
    name: '이스탄불',
    country: '튀르키예',
    flag: '🇹🇷',
    styles: JSON.stringify(['culture', 'food', 'city', 'history']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 1500000,
    rating: 4.9,
    bestSeason: '4월-6월, 9월-11월',
    pros: JSON.stringify(['동서양 문화 융합', '음식 매우 맛있음', '역사 유적 풍부', '가성비 좋음']),
    cons: JSON.stringify(['비행시간 길다', '여름 매우 더움']),
    description: '동서양이 만나는 곳! 역사, 미식, 자연이 어우러진 매력적인 여행지',
    highlights: JSON.stringify(['카파도키아 열기구', '아야 소피아', '그랜드 바자르', '파묵칼레', '보스포루스 크루즈']),
    sampleItinerary: JSON.stringify({ days: 7, perDayCost: 200000, mustDo: ['카파도키아 열기구 투어', '그랜드 바자르 쇼핑', '보스포루스 선셋 크루즈'] })
  },
  {
    id: 'greece-santorini',
    name: '산토리니',
    country: '그리스',
    flag: '🇬🇷',
    styles: JSON.stringify(['beach', 'relaxation', 'culture']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple']),
    flightTime: 'long',
    avgCost: 2000000,
    rating: 4.8,
    bestSeason: '5월-10월',
    pros: JSON.stringify(['환상적인 석양', '화이트&블루 마을', '로맨틱 분위기']),
    cons: JSON.stringify(['물가 비쌈', '비행 환승 필요']),
    description: '하얀 건물과 푸른 바다가 만나는 로맨틱한 섬',
    highlights: JSON.stringify(['이아 석양', '블루돔 교회', '화산섬 투어', '와이너리']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 400000, mustDo: ['이아 석양 감상', '블루돔 사진', '와인 투어'] })
  },
  {
    id: 'italy-rome',
    name: '로마',
    country: '이탈리아',
    flag: '🇮🇹',
    styles: JSON.stringify(['culture', 'food', 'city', 'history']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'long',
    avgCost: 1800000,
    rating: 4.8,
    bestSeason: '4월-6월, 9월-10월',
    pros: JSON.stringify(['역사 유적 풍부', '음식 천국', '예술과 문화']),
    cons: JSON.stringify(['관광객 많음', '소매치기 주의']),
    description: '2000년 역사가 살아 숨쉬는 영원의 도시',
    highlights: JSON.stringify(['콜로세움', '바티칸 시국', '트레비 분수', '판테온']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 350000, mustDo: ['콜로세움 투어', '바티칸 박물관', '트레비 분수'] })
  },
  {
    id: 'france-paris',
    name: '파리',
    country: '프랑스',
    flag: '🇫🇷',
    styles: JSON.stringify(['culture', 'city', 'food']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'solo']),
    flightTime: 'long',
    avgCost: 2200000,
    rating: 4.7,
    bestSeason: '4월-6월, 9월-10월',
    pros: JSON.stringify(['로맨틱한 분위기', '예술과 문화', '미식의 도시']),
    cons: JSON.stringify(['물가 매우 비쌈', '영어 잘 안 통함']),
    description: '로맨스와 예술의 도시, 세계 문화의 중심',
    highlights: JSON.stringify(['에펠탑', '루브르 박물관', '몽마르트 언덕', '샹젤리제']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 450000, mustDo: ['에펠탑 야경', '루브르 관람', '세느강 크루즈'] })
  },
  {
    id: 'spain-barcelona',
    name: '바르셀로나',
    country: '스페인',
    flag: '🇪🇸',
    styles: JSON.stringify(['culture', 'beach', 'city', 'food']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'long',
    avgCost: 1600000,
    rating: 4.8,
    bestSeason: '5월-10월',
    pros: JSON.stringify(['가우디 건축', '해변과 도시 모두', '음식 맛있음']),
    cons: JSON.stringify(['소매치기 많음', '여름 관광객 폭주']),
    description: '가우디의 예술과 지중해가 만나는 곳',
    highlights: JSON.stringify(['사그라다 파밀리아', '구엘 공원', '람블라스 거리', '바르셀로네타 해변']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 320000, mustDo: ['사그라다 파밀리아', '구엘공원', '타파스 투어'] })
  },
  {
    id: 'uk-london',
    name: '런던',
    country: '영국',
    flag: '🇬🇧',
    styles: JSON.stringify(['city', 'culture', 'shopping', 'history']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo', 'family']),
    flightTime: 'long',
    avgCost: 2500000,
    rating: 4.7,
    bestSeason: '5월-9월',
    pros: JSON.stringify(['영어 통함', '박물관 대부분 무료', '다양한 문화', '대중교통 편리']),
    cons: JSON.stringify(['물가 매우 비쌈', '날씨 변덕', '음식 별로']),
    description: '역사와 현대가 공존하는 세계적인 대도시',
    highlights: JSON.stringify(['대영박물관', '빅벤', '타워 브릿지', '버킹엄 궁전', '해리포터 스튜디오']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 500000, mustDo: ['대영박물관', '해리포터 투어', '애프터눈 티'] })
  },
  {
    id: 'germany-munich',
    name: '뮌헨',
    country: '독일',
    flag: '🇩🇪',
    styles: JSON.stringify(['culture', 'food', 'city', 'history']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['friends', 'couple', 'family']),
    flightTime: 'long',
    avgCost: 1700000,
    rating: 4.6,
    bestSeason: '5월-10월 (옥토버페스트 9월)',
    pros: JSON.stringify(['맥주 천국', '노이슈반슈타인 성 근처', '대중교통 좋음', '깨끗함']),
    cons: JSON.stringify(['겨울 춥고 어두움', '영어 잘 안 통하는 곳 있음']),
    description: '맥주와 성(城)의 도시, 바이에른의 심장',
    highlights: JSON.stringify(['노이슈반슈타인 성', '마리엔 광장', 'BMW 박물관', '영국정원']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 350000, mustDo: ['노이슈반슈타인 성 투어', '호프브로이하우스 맥주', '님펜부르크 궁전'] })
  },
  {
    id: 'switzerland-interlaken',
    name: '인터라켄',
    country: '스위스',
    flag: '🇨🇭',
    styles: JSON.stringify(['nature', 'adventure', 'relaxation']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'family', 'friends']),
    flightTime: 'long',
    avgCost: 2800000,
    rating: 4.9,
    bestSeason: '6월-9월 (겨울 스키 12월-3월)',
    pros: JSON.stringify(['알프스 절경', '융프라우 등산', '깨끗하고 안전', '다양한 액티비티']),
    cons: JSON.stringify(['물가 매우 비쌈', '날씨 변덕']),
    description: '알프스의 보석, 융프라우와 두 호수 사이의 천국',
    highlights: JSON.stringify(['융프라우', '쉴트호른', '하더 쿨름', '패러글라이딩', '트럼멜바흐 폭포']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 600000, mustDo: ['융프라우 등산 열차', '패러글라이딩', '라우터브룬넨 계곡'] })
  },
  {
    id: 'netherlands-amsterdam',
    name: '암스테르담',
    country: '네덜란드',
    flag: '🇳🇱',
    styles: JSON.stringify(['city', 'culture', 'shopping']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 1900000,
    rating: 4.6,
    bestSeason: '4월-10월 (튤립 4월)',
    pros: JSON.stringify(['자전거 문화', '운하 아름다움', '영어 잘 통함', '박물관 풍부']),
    cons: JSON.stringify(['관광객 많음', '비싼 물가']),
    description: '운하와 자전거의 도시, 예술과 자유의 천국',
    highlights: JSON.stringify(['안네 프랑크의 집', '반 고흐 박물관', '잔세스칸스 풍차', '튤립 축제']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 400000, mustDo: ['운하 크루즈', '반 고흐 박물관', '풍차마을'] })
  },
  {
    id: 'portugal-lisbon',
    name: '리스본',
    country: '포르투갈',
    flag: '🇵🇹',
    styles: JSON.stringify(['city', 'culture', 'food', 'beach']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 1400000,
    rating: 4.7,
    bestSeason: '5월-10월',
    pros: JSON.stringify(['저렴한 물가', '음식 맛있음', '날씨 좋음', '사람들 친절']),
    cons: JSON.stringify(['언덕 많음', '대중교통 불편']),
    description: '7개 언덕의 도시, 노란 트램과 에그타르트의 본고장',
    highlights: JSON.stringify(['벨렝 타워', '제로니무스 수도원', '28번 트램', '알파마 지구']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 250000, mustDo: ['28번 트램 탑승', '에그타르트 맛집', '신트라 당일치기'] })
  },
  {
    id: 'czech-prague',
    name: '프라하',
    country: '체코',
    flag: '🇨🇿',
    styles: JSON.stringify(['city', 'culture', 'history']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends']),
    flightTime: 'long',
    avgCost: 1300000,
    rating: 4.7,
    bestSeason: '5월-9월',
    pros: JSON.stringify(['저렴한 물가', '중세 건축 아름다움', '맥주 저렴', '치안 좋음']),
    cons: JSON.stringify(['관광객 많음', '소매치기 주의']),
    description: '동유럽의 파리, 중세 동화 속 같은 도시',
    highlights: JSON.stringify(['카를교', '프라하 성', '천문시계', '구시가지 광장']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 200000, mustDo: ['카를교 일출', '프라하 성', '맥주 투어'] })
  },
  {
    id: 'austria-vienna',
    name: '빈',
    country: '오스트리아',
    flag: '🇦🇹',
    styles: JSON.stringify(['city', 'culture', 'music', 'history']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'family', 'solo']),
    flightTime: 'long',
    avgCost: 1800000,
    rating: 4.7,
    bestSeason: '4월-10월',
    pros: JSON.stringify(['클래식 음악의 도시', '궁전 아름다움', '커피 문화', '대중교통 편리']),
    cons: JSON.stringify(['물가 비쌈', '영어 잘 안 통하는 곳 있음']),
    description: '음악의 수도, 합스부르크 왕가의 영광이 살아있는 도시',
    highlights: JSON.stringify(['쉔브룬 궁전', '빈 국립 오페라', '슈테판 대성당', '벨베데레 궁전']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 350000, mustDo: ['쉔브룬 궁전', '오페라 관람', '카페 문화 체험'] })
  },
  {
    id: 'croatia-dubrovnik',
    name: '두브로브니크',
    country: '크로아티아',
    flag: '🇭🇷',
    styles: JSON.stringify(['beach', 'culture', 'history']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends']),
    flightTime: 'long',
    avgCost: 1500000,
    rating: 4.8,
    bestSeason: '5월-9월',
    pros: JSON.stringify(['아드리아해 절경', '왕좌의 게임 촬영지', '성벽 도시', '물가 적당']),
    cons: JSON.stringify(['여름 관광객 폭주', '해변 자갈']),
    description: '아드리아해의 진주, 중세 성벽 도시',
    highlights: JSON.stringify(['성벽 워킹', '케이블카', '로크룸 섬', '스폰자 궁전']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 300000, mustDo: ['성벽 일주', '케이블카 석양', '왕좌의 게임 투어'] })
  },
  {
    id: 'iceland-reykjavik',
    name: '레이캬비크',
    country: '아이슬란드',
    flag: '🇮🇸',
    styles: JSON.stringify(['nature', 'adventure', 'relaxation']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 2500000,
    rating: 4.9,
    bestSeason: '6월-8월 (오로라 9월-3월)',
    pros: JSON.stringify(['오로라', '빙하', '온천', '독특한 자연경관']),
    cons: JSON.stringify(['물가 매우 비쌈', '겨울 매우 춥고 어두움', '렌터카 필수']),
    description: '불과 얼음의 나라, 오로라와 빙하의 천국',
    highlights: JSON.stringify(['블루라군', '골든서클', '오로라', '빙하 하이킹', '검은 모래 해변']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 500000, mustDo: ['골든서클 투어', '블루라군', '오로라 헌팅'] })
  },
  {
    id: 'norway-bergen',
    name: '베르겐',
    country: '노르웨이',
    flag: '🇳🇴',
    styles: JSON.stringify(['nature', 'city', 'culture']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'family', 'friends']),
    flightTime: 'long',
    avgCost: 2400000,
    rating: 4.8,
    bestSeason: '5월-9월',
    pros: JSON.stringify(['피오르드 절경', '깨끗한 자연', '생선 시장', '귀여운 목조 가옥']),
    cons: JSON.stringify(['물가 매우 비쌈', '비 자주 옴']),
    description: '피오르드의 관문, 무지개 색 브뤼겐 가옥',
    highlights: JSON.stringify(['브뤼겐 지구', '플뢰엔 산', '송네피오르드', '어시장']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 500000, mustDo: ['송네피오르드 크루즈', '플뢰엔 등산', '어시장 투어'] })
  },

  // ========================================
  // 아시아 (35개)
  // ========================================
  {
    id: 'japan-tokyo',
    name: '도쿄',
    country: '일본',
    flag: '🇯🇵',
    styles: JSON.stringify(['shopping', 'city', 'food']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['solo', 'couple', 'friends']),
    flightTime: 'short',
    avgCost: 800000,
    rating: 4.8,
    bestSeason: '봄(3-5월), 가을(9-11월)',
    pros: JSON.stringify(['가까워서 편함', '음식 맛있음', '대중교통 편리', '안전함']),
    cons: JSON.stringify(['물가 조금 비쌈', '사람 많음']),
    description: '쇼핑과 미식의 천국! 편의점 음식도 맛있고, 볼거리 가득한 도시',
    highlights: JSON.stringify(['시부야 스크램블', '센소지', '아키하바라', '츠키지 시장']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 200000, mustDo: ['하라주쿠 거리 산책', '스카이트리 전망', '이자카야 투어'] })
  },
  {
    id: 'japan-osaka',
    name: '오사카',
    country: '일본',
    flag: '🇯🇵',
    styles: JSON.stringify(['food', 'city', 'shopping', 'family']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['solo', 'couple', 'friends', 'family']),
    flightTime: 'short',
    avgCost: 750000,
    rating: 4.7,
    bestSeason: '봄(3-5월), 가을(9-11월)',
    pros: JSON.stringify(['먹거리 천국', '도쿄보다 저렴', '사람들 친절', '교토 근처']),
    cons: JSON.stringify(['관광지는 도쿄보다 적음']),
    description: '일본의 부엌! 길거리 음식과 타코야키의 성지',
    highlights: JSON.stringify(['도톤보리', 'USJ', '오사카성', '신세카이']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 180000, mustDo: ['도톤보리 야경', 'USJ 풀데이', '구로몬 시장 투어'] })
  },
  {
    id: 'japan-kyoto',
    name: '교토',
    country: '일본',
    flag: '🇯🇵',
    styles: JSON.stringify(['culture', 'history', 'nature', 'relaxation']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'solo', 'family']),
    flightTime: 'short',
    avgCost: 850000,
    rating: 4.9,
    bestSeason: '봄(벚꽃 3-4월), 가을(단풍 11월)',
    pros: JSON.stringify(['일본 전통 문화', '사찰 아름다움', '조용하고 평화로움', '사계절 아름다움']),
    cons: JSON.stringify(['관광객 많음', '버스 복잡']),
    description: '천년의 고도, 일본 전통미의 정수',
    highlights: JSON.stringify(['후시미 이나리', '금각사', '기요미즈데라', '아라시야마 대나무숲', '기온 게이샤 거리']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 220000, mustDo: ['후시미 이나리 등산', '아라시야마 대나무숲', '전통 료칸 숙박'] })
  },
  {
    id: 'japan-okinawa',
    name: '오키나와',
    country: '일본',
    flag: '🇯🇵',
    styles: JSON.stringify(['beach', 'nature', 'relaxation', 'family']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['family', 'couple']),
    flightTime: 'short',
    avgCost: 1000000,
    rating: 4.6,
    bestSeason: '4월-6월, 9월-11월',
    pros: JSON.stringify(['깨끗한 바다', '가족 친화', '미군기지 문화', '수족관 최고']),
    cons: JSON.stringify(['렌터카 필수', '태풍 시즌 주의']),
    description: '일본의 하와이! 에메랄드빛 바다와 독특한 류큐 문화',
    highlights: JSON.stringify(['추라우미 수족관', '만좌모', '아메리칸 빌리지', '나하 국제거리']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 200000, mustDo: ['추라우미 수족관', '블루 케이브 스노클링', '나하 거리 산책'] })
  },
  {
    id: 'korea-jeju',
    name: '제주도',
    country: '한국',
    flag: '🇰🇷',
    styles: JSON.stringify(['nature', 'relaxation', 'food', 'family']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['family', 'couple', 'friends']),
    flightTime: 'short',
    avgCost: 500000,
    rating: 4.4,
    bestSeason: '4월-6월, 9월-11월',
    pros: JSON.stringify(['가까움', '언어 편함', '자연 좋음', '음식 맛있음']),
    cons: JSON.stringify(['날씨 변덕', '렌터카 필수']),
    description: '부담없는 국내 여행! 한라산과 바다를 동시에',
    highlights: JSON.stringify(['한라산', '성산일출봉', '우도', '협재해수욕장']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 150000, mustDo: ['성산일출봉 일출', '우도 사이클링', '흑돼지 맛집'] })
  },
  {
    id: 'thailand-bangkok',
    name: '방콕',
    country: '태국',
    flag: '🇹🇭',
    styles: JSON.stringify(['relaxation', 'food', 'city', 'shopping']),
    budgetRange: JSON.stringify(['low']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'medium',
    avgCost: 600000,
    rating: 4.6,
    bestSeason: '11월-2월 (건기)',
    pros: JSON.stringify(['저렴함', '음식 맛있음', '마사지 천국', '야시장 재미']),
    cons: JSON.stringify(['더움', '습함', '교통 혼잡']),
    description: '가성비 최고! 저렴하게 즐기는 동남아 여행',
    highlights: JSON.stringify(['왕궁', '카오산 로드', '짜뚜짝 시장', '왓 아룬']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 100000, mustDo: ['수상시장 투어', '루프탑 바', '태국 마사지'] })
  },
  {
    id: 'thailand-phuket',
    name: '푸켓',
    country: '태국',
    flag: '🇹🇭',
    styles: JSON.stringify(['beach', 'relaxation', 'adventure']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'medium',
    avgCost: 700000,
    rating: 4.5,
    bestSeason: '11월-4월',
    pros: JSON.stringify(['아름다운 해변', '저렴한 물가', '다양한 액티비티', '나이트라이프']),
    cons: JSON.stringify(['우기 비 많음', '관광지화', '바가지 주의']),
    description: '안다만해의 진주, 해변 리조트의 천국',
    highlights: JSON.stringify(['빠통 비치', '피피섬', '팡아 베이', '빅부다', '푸켓 판타씨']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 150000, mustDo: ['피피섬 투어', '팡아베이 카약', '타이 마사지'] })
  },
  {
    id: 'vietnam-danang',
    name: '다낭',
    country: '베트남',
    flag: '🇻🇳',
    styles: JSON.stringify(['relaxation', 'nature', 'food', 'beach']),
    budgetRange: JSON.stringify(['low']),
    bestFor: JSON.stringify(['couple', 'family']),
    flightTime: 'medium',
    avgCost: 700000,
    rating: 4.5,
    bestSeason: '2월-5월',
    pros: JSON.stringify(['해변 아름다움', '저렴함', '음식 맛있음', '한국인 많아 편함']),
    cons: JSON.stringify(['영어 잘 안 통함', '비오는 날 많음']),
    description: '힐링 해변 여행! 아름다운 바다와 저렴한 물가',
    highlights: JSON.stringify(['미케비치', '바나힐', '호이안 야경', '마블 마운틴']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 120000, mustDo: ['바나힐 골든 브릿지', '호이안 랜턴 축제', '미케비치 선셋'] })
  },
  {
    id: 'vietnam-hochiminh',
    name: '호치민',
    country: '베트남',
    flag: '🇻🇳',
    styles: JSON.stringify(['city', 'food', 'culture', 'shopping']),
    budgetRange: JSON.stringify(['low']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'medium',
    avgCost: 650000,
    rating: 4.4,
    bestSeason: '12월-4월',
    pros: JSON.stringify(['저렴함', '쌀국수 천국', '프랑스 건축', '활기찬 분위기']),
    cons: JSON.stringify(['교통 혼잡', '매연', '더움']),
    description: '프랑스 향기가 남아있는 동남아 대도시',
    highlights: JSON.stringify(['노트르담 대성당', '벤탄 시장', '전쟁박물관', '메콩강 투어']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 100000, mustDo: ['쿠치터널 투어', '메콩강 크루즈', '쌀국수 맛집 투어'] })
  },
  {
    id: 'singapore-main',
    name: '싱가포르',
    country: '싱가포르',
    flag: '🇸🇬',
    styles: JSON.stringify(['city', 'food', 'family', 'shopping']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['family', 'couple', 'friends']),
    flightTime: 'medium',
    avgCost: 1200000,
    rating: 4.7,
    bestSeason: '연중 가능 (건기: 2-4월)',
    pros: JSON.stringify(['깨끗함', '안전함', '영어 통함', '다양한 문화']),
    cons: JSON.stringify(['물가 비쌈', '작은 도시']),
    description: '도시국가의 매력! 깨끗하고 안전한 가족 여행지',
    highlights: JSON.stringify(['마리나베이 샌즈', '가든스 바이 더 베이', '센토사', 'USS']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 250000, mustDo: ['마리나베이 야경', '센토사 USS', '호커센터 맛집 투어'] })
  },
  {
    id: 'indonesia-bali',
    name: '발리',
    country: '인도네시아',
    flag: '🇮🇩',
    styles: JSON.stringify(['relaxation', 'nature', 'adventure', 'beach']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends']),
    flightTime: 'medium',
    avgCost: 900000,
    rating: 4.7,
    bestSeason: '4월-10월 (건기)',
    pros: JSON.stringify(['힐링 최고', '리조트 저렴', '자연 아름다움', '서핑 가능']),
    cons: JSON.stringify(['우기엔 비 많음', '교통 불편']),
    description: '신들의 섬! 힐링과 액티비티를 동시에',
    highlights: JSON.stringify(['우붓 라이스테라스', '따나롯 사원', '누사페니다', '짐바란 비치']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 150000, mustDo: ['우붓 원숭이숲', '스노클링', '선셋 디너'] })
  },
  {
    id: 'philippines-boracay',
    name: '보라카이',
    country: '필리핀',
    flag: '🇵🇭',
    styles: JSON.stringify(['beach', 'relaxation', 'adventure']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'medium',
    avgCost: 800000,
    rating: 4.6,
    bestSeason: '11월-5월 (건기)',
    pros: JSON.stringify(['화이트 비치 아름다움', '저렴함', '다양한 해양 액티비티', '영어 통함']),
    cons: JSON.stringify(['우기 피해야 함', '교통 불편', '환경오염 우려']),
    description: '세계 최고의 화이트 비치, 해양 스포츠의 천국',
    highlights: JSON.stringify(['화이트 비치', '푸카 셸 비치', '스노클링', '패러세일링', '선셋 세일링']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 150000, mustDo: ['화이트비치 선셋', '아일랜드 호핑', '해양 스포츠'] })
  },
  {
    id: 'malaysia-kualalumpur',
    name: '쿠알라룸푸르',
    country: '말레이시아',
    flag: '🇲🇾',
    styles: JSON.stringify(['city', 'shopping', 'food', 'culture']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['family', 'friends', 'couple']),
    flightTime: 'medium',
    avgCost: 700000,
    rating: 4.5,
    bestSeason: '12월-2월',
    pros: JSON.stringify(['저렴함', '쇼핑천국', '영어 통함', '다문화 음식']),
    cons: JSON.stringify(['더움', '습함', '대중교통 불편']),
    description: '다문화 도시, 쇼핑과 미식의 천국',
    highlights: JSON.stringify(['페트로나스 트윈타워', '바투 동굴', '부킷 빈탕', '센트럴 마켓']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 120000, mustDo: ['트윈타워 야경', '바투동굴', '호커센터 투어'] })
  },
  {
    id: 'china-beijing',
    name: '베이징',
    country: '중국',
    flag: '🇨🇳',
    styles: JSON.stringify(['culture', 'history', 'city']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['family', 'friends', 'solo']),
    flightTime: 'short',
    avgCost: 900000,
    rating: 4.6,
    bestSeason: '4월-6월, 9월-10월',
    pros: JSON.stringify(['역사 유적 풍부', '만리장성', '저렴한 물가', '가까움']),
    cons: JSON.stringify(['미세먼지', '영어 안 통함', 'VPN 필요']),
    description: '중국의 심장, 만리장성과 자금성',
    highlights: JSON.stringify(['만리장성', '자금성', '천단공원', '왕푸징 거리']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 150000, mustDo: ['만리장성 등반', '자금성 투어', '베이징 덕 맛집'] })
  },
  {
    id: 'china-shanghai',
    name: '상하이',
    country: '중국',
    flag: '🇨🇳',
    styles: JSON.stringify(['city', 'shopping', 'culture', 'food']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'short',
    avgCost: 950000,
    rating: 4.5,
    bestSeason: '3월-5월, 9월-11월',
    pros: JSON.stringify(['현대와 전통 공존', '야경 아름다움', '쇼핑천국', '가까움']),
    cons: JSON.stringify(['물가 비쌈', '영어 안 통함', 'VPN 필요']),
    description: '동방의 파리, 과거와 미래가 공존하는 메트로폴리스',
    highlights: JSON.stringify(['와이탄', '예원', '상하이 타워', '난징루', '디즈니랜드']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 200000, mustDo: ['와이탄 야경', '예원 산책', '디즈니랜드'] })
  },
  {
    id: 'taiwan-taipei',
    name: '타이베이',
    country: '대만',
    flag: '🇹🇼',
    styles: JSON.stringify(['city', 'food', 'shopping', 'culture']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo', 'family']),
    flightTime: 'short',
    avgCost: 800000,
    rating: 4.7,
    bestSeason: '10월-12월',
    pros: JSON.stringify(['음식 천국', '저렴함', '친절함', '야시장 재미', '한자 읽힘']),
    cons: JSON.stringify(['여름 덥고 습함', '태풍 시즌 주의']),
    description: '미식의 천국, 야시장과 랜턴의 도시',
    highlights: JSON.stringify(['타이베이 101', '스린 야시장', '지우펀', '지메이 온천', '중정기념당']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 150000, mustDo: ['스린 야시장 투어', '지우펀 석양', '샤오롱바오 맛집'] })
  },
  {
    id: 'hongkong-main',
    name: '홍콩',
    country: '홍콩',
    flag: '🇭🇰',
    styles: JSON.stringify(['city', 'shopping', 'food', 'culture']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'medium',
    avgCost: 1100000,
    rating: 4.6,
    bestSeason: '10월-12월',
    pros: JSON.stringify(['야경 아름다움', '쇼핑천국', '딤섬 맛있음', '대중교통 편리']),
    cons: JSON.stringify(['물가 비쌈', '습함', '좁음']),
    description: '동양의 진주, 마천루와 빅토리아 항구의 야경',
    highlights: JSON.stringify(['빅토리아 피크', '침사추이 야경', '디즈니랜드', '란타우섬 빅부다', '몽콕 야시장']),
    sampleItinerary: JSON.stringify({ days: 3, perDayCost: 250000, mustDo: ['빅토리아 피크 야경', '딤섬 맛집', '디즈니랜드'] })
  },
  {
    id: 'macau-main',
    name: '마카오',
    country: '마카오',
    flag: '🇲🇴',
    styles: JSON.stringify(['city', 'culture', 'shopping', 'food']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends']),
    flightTime: 'medium',
    avgCost: 900000,
    rating: 4.5,
    bestSeason: '10월-12월',
    pros: JSON.stringify(['카지노', '포르투갈 문화', '에그타르트', '홍콩 근처']),
    cons: JSON.stringify(['좁음', '카지노 중심', '물가 비쌈']),
    description: '동양의 라스베가스, 포르투갈 향기가 남은 도시',
    highlights: JSON.stringify(['세나도 광장', '베네시안 호텔', '성 바울 성당', '마카오 타워']),
    sampleItinerary: JSON.stringify({ days: 2, perDayCost: 200000, mustDo: ['세나도 광장', '에그타르트 맛집', '베네시안 호텔'] })
  },
  {
    id: 'maldives-male',
    name: '몰디브',
    country: '몰디브',
    flag: '🇲🇻',
    styles: JSON.stringify(['beach', 'relaxation', 'nature']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple']),
    flightTime: 'long',
    avgCost: 3500000,
    rating: 4.9,
    bestSeason: '11월-4월',
    pros: JSON.stringify(['천국 같은 바다', '프라이빗 리조트', '스노클링/다이빙 최고', '허니문 천국']),
    cons: JSON.stringify(['매우 비쌈', '할 일 없음', '리조트 외 볼거리 없음']),
    description: '인도양의 천국, 수상 방갈로와 에메랄드빛 바다',
    highlights: JSON.stringify(['수상 방갈로', '스노클링', '다이빙', '선셋 크루즈', '돌고래 투어']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 700000, mustDo: ['수상 방갈로 숙박', '스노클링', '선셋 크루즈'] })
  },
  {
    id: 'srilanka-colombo',
    name: '스리랑카',
    country: '스리랑카',
    flag: '🇱🇰',
    styles: JSON.stringify(['nature', 'culture', 'adventure', 'beach']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'medium',
    avgCost: 1200000,
    rating: 4.6,
    bestSeason: '12월-3월',
    pros: JSON.stringify(['저렴함', '다양한 볼거리', '홍차', '사파리', '친절함']),
    cons: JSON.stringify(['교통 불편', '인프라 부족']),
    description: '인도양의 진주, 홍차와 사파리의 나라',
    highlights: JSON.stringify(['시기리야 바위', '차밭 투어', '고래 투어', '골', '해변 리조트']),
    sampleItinerary: JSON.stringify({ days: 7, perDayCost: 150000, mustDo: ['시기리야 등반', '차밭 투어', '고래 투어'] })
  },
  {
    id: 'nepal-kathmandu',
    name: '카트만두',
    country: '네팔',
    flag: '🇳🇵',
    styles: JSON.stringify(['adventure', 'nature', 'culture']),
    budgetRange: JSON.stringify(['low']),
    bestFor: JSON.stringify(['solo', 'friends', 'couple']),
    flightTime: 'medium',
    avgCost: 1000000,
    rating: 4.7,
    bestSeason: '10월-11월, 3월-5월',
    pros: JSON.stringify(['트레킹 천국', '히말라야', '저렴함', '문화 체험']),
    cons: JSON.stringify(['인프라 부족', '더스트', '고산병 주의']),
    description: '히말라야의 관문, 트레킹과 영성의 나라',
    highlights: JSON.stringify(['에베레스트 베이스캠프', '안나푸르나 트레킹', '보드나트 사원', '더르바르 광장']),
    sampleItinerary: JSON.stringify({ days: 10, perDayCost: 100000, mustDo: ['안나푸르나 트레킹', '포카라 패러글라이딩', '사원 투어'] })
  },
  {
    id: 'india-delhi',
    name: '델리',
    country: '인도',
    flag: '🇮🇳',
    styles: JSON.stringify(['culture', 'history', 'food', 'city']),
    budgetRange: JSON.stringify(['low']),
    bestFor: JSON.stringify(['solo', 'friends', 'couple']),
    flightTime: 'medium',
    avgCost: 1100000,
    rating: 4.4,
    bestSeason: '10월-3월',
    pros: JSON.stringify(['매우 저렴함', '카레 본고장', '역사 유적', '타지마할 근처']),
    cons: JSON.stringify(['위생 주의', '바가지 많음', '소음/공기 오염', '치안 주의']),
    description: '혼돈과 신비의 도시, 인도의 심장',
    highlights: JSON.stringify(['타지마할(아그라)', '붉은 요새', '후마윤 묘', '로터스 템플', '인도 게이트']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 100000, mustDo: ['타지마할 투어', '인도 요리 체험', '붉은 요새'] })
  },
  {
    id: 'uae-dubai',
    name: '두바이',
    country: '아랍에미리트',
    flag: '🇦🇪',
    styles: JSON.stringify(['city', 'shopping', 'adventure', 'beach']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'family', 'friends']),
    flightTime: 'long',
    avgCost: 2500000,
    rating: 4.7,
    bestSeason: '11월-3월',
    pros: JSON.stringify(['초고층 빌딩', '럭셔리 쇼핑', '사막 사파리', '안전함', '면세 천국']),
    cons: JSON.stringify(['매우 비쌈', '여름 극도로 더움', '알코올 제한']),
    description: '사막의 기적, 초고층 빌딩과 럭셔리의 도시',
    highlights: JSON.stringify(['부르즈 할리파', '두바이 몰', '팜 주메이라', '사막 사파리', '두바이 마리나']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 500000, mustDo: ['부르즈 할리파 전망대', '사막 사파리', '두바이몰 쇼핑'] })
  },

  // ========================================
  // 아메리카 (20개)
  // ========================================
  {
    id: 'usa-hawaii',
    name: '하와이',
    country: '미국',
    flag: '🇺🇸',
    styles: JSON.stringify(['beach', 'nature', 'relaxation', 'adventure']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'family', 'friends']),
    flightTime: 'long',
    avgCost: 2500000,
    rating: 4.8,
    bestSeason: '4월-10월',
    pros: JSON.stringify(['천혜의 자연', '다양한 액티비티', '한국어 가능', '쇼핑']),
    cons: JSON.stringify(['비쌈', '비행시간 긺', '시차 큼']),
    description: '꿈의 휴양지! 완벽한 해변과 다채로운 액티비티',
    highlights: JSON.stringify(['와이키키 비치', '다이아몬드 헤드', '노스쇼어', '쿠알로아 랜치']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 400000, mustDo: ['다이아몬드 헤드 하이킹', '쿠알로아 랜치 투어', '선셋 크루즈'] })
  },
  {
    id: 'usa-newyork',
    name: '뉴욕',
    country: '미국',
    flag: '🇺🇸',
    styles: JSON.stringify(['city', 'culture', 'shopping', 'food']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 2800000,
    rating: 4.8,
    bestSeason: '4월-6월, 9월-11월',
    pros: JSON.stringify(['세계 중심 도시', '뮤지컬 천국', '박물관 풍부', '24시간 도시']),
    cons: JSON.stringify(['매우 비쌈', '치안 주의', '복잡함']),
    description: '세계의 수도, 꿈과 기회의 도시',
    highlights: JSON.stringify(['자유의 여신상', '센트럴 파크', '타임스퀘어', '브루클린 브릿지', '브로드웨이']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 500000, mustDo: ['브로드웨이 뮤지컬', '자유의 여신상', '센트럴파크 산책'] })
  },
  {
    id: 'usa-la',
    name: '로스앤젤레스',
    country: '미국',
    flag: '🇺🇸',
    styles: JSON.stringify(['city', 'beach', 'shopping', 'culture']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['family', 'couple', 'friends']),
    flightTime: 'long',
    avgCost: 2600000,
    rating: 4.6,
    bestSeason: '연중 가능',
    pros: JSON.stringify(['날씨 좋음', '할리우드', '해변', '한인타운', '테마파크']),
    cons: JSON.stringify(['차 필수', '교통 체증', '비쌈']),
    description: '천사들의 도시, 할리우드와 해변의 천국',
    highlights: JSON.stringify(['유니버설 스튜디오', '디즈니랜드', '할리우드', '산타모니카', '베니스 비치']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 450000, mustDo: ['유니버설 스튜디오', '산타모니카 선셋', '할리우드 산책'] })
  },
  {
    id: 'usa-lasvegas',
    name: '라스베가스',
    country: '미국',
    flag: '🇺🇸',
    styles: JSON.stringify(['city', 'adventure', 'shopping']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['friends', 'couple']),
    flightTime: 'long',
    avgCost: 2200000,
    rating: 4.7,
    bestSeason: '3월-5월, 9월-11월',
    pros: JSON.stringify(['카지노', '쇼 천국', '그랜드캐년 근처', '24시간 도시', '면세']),
    cons: JSON.stringify(['여름 극도로 더움', '술/담배 제한', '비쌈']),
    description: '불야성의 도시, 카지노와 쇼의 천국',
    highlights: JSON.stringify(['벨라지오 분수', '프리몬트 거리', '그랜드 캐년', '후버댐', '시르크 뒤 솔레이유']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 400000, mustDo: ['그랜드 캐년 투어', '벨라지오 분수', '시르크 쇼'] })
  },
  {
    id: 'usa-sanfrancisco',
    name: '샌프란시스코',
    country: '미국',
    flag: '🇺🇸',
    styles: JSON.stringify(['city', 'culture', 'nature']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 2700000,
    rating: 4.7,
    bestSeason: '9월-11월',
    pros: JSON.stringify(['금문교', 'IT 성지', '케이블카', '다양한 문화', '아름다운 경관']),
    cons: JSON.stringify(['매우 비쌈', '안개 많음', '언덕 많음']),
    description: 'IT의 성지, 금문교와 케이블카의 도시',
    highlights: JSON.stringify(['금문교', '알카트라즈', '피어39', '롬바드 거리', '케이블카']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 500000, mustDo: ['금문교 자전거', '알카트라즈 투어', '케이블카 탑승'] })
  },
  {
    id: 'canada-vancouver',
    name: '밴쿠버',
    country: '캐나다',
    flag: '🇨🇦',
    styles: JSON.stringify(['city', 'nature', 'culture']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'family', 'friends']),
    flightTime: 'long',
    avgCost: 2000000,
    rating: 4.7,
    bestSeason: '6월-9월',
    pros: JSON.stringify(['자연 아름다움', '깨끗함', '안전함', '다문화', '한인 많음']),
    cons: JSON.stringify(['비쌈', '겨울 비 많음']),
    description: '산과 바다가 만나는 도시, 세계에서 가장 살기 좋은 도시',
    highlights: JSON.stringify(['스탠리 파크', '그라우스 마운틴', '캐필라노 현수교', '개스타운']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 350000, mustDo: ['캐필라노 현수교', '스탠리파크 자전거', '그라우스 마운틴'] })
  },
  {
    id: 'canada-toronto',
    name: '토론토',
    country: '캐나다',
    flag: '🇨🇦',
    styles: JSON.stringify(['city', 'culture', 'nature']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'family', 'friends']),
    flightTime: 'long',
    avgCost: 2100000,
    rating: 4.6,
    bestSeason: '6월-9월',
    pros: JSON.stringify(['다문화 도시', '나이아가라 폭포 근처', '안전함', '깨끗함']),
    cons: JSON.stringify(['겨울 매우 춥고 긺', '비쌈']),
    description: '캐나다 최대 도시, 나이아가라 폭포의 관문',
    highlights: JSON.stringify(['CN 타워', '나이아가라 폭포', '로저스 센터', '디스틸러리 지구']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 350000, mustDo: ['나이아가라 폭포 투어', 'CN타워 전망대', '디스틸러리 지구'] })
  },
  {
    id: 'mexico-cancun',
    name: '칸쿤',
    country: '멕시코',
    flag: '🇲🇽',
    styles: JSON.stringify(['beach', 'relaxation', 'adventure', 'culture']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'long',
    avgCost: 1800000,
    rating: 4.7,
    bestSeason: '12월-4월',
    pros: JSON.stringify(['카리브해 절경', '올인클루시브 리조트', '마야 유적', '세노테']),
    cons: JSON.stringify(['비행시간 매우 긺', '허리케인 시즌 주의', '영어 잘 안 통함']),
    description: '카리브해의 천국, 마야 유적과 에메랄드빛 바다',
    highlights: JSON.stringify(['치첸이트사', '세노테 수영', '플라야 델 카르멘', '툴룸', '이슬라 무헤레스']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 300000, mustDo: ['치첸이트사 투어', '세노테 다이빙', '이슬라 무헤레스'] })
  },
  {
    id: 'mexico-mexicocity',
    name: '멕시코시티',
    country: '멕시코',
    flag: '🇲🇽',
    styles: JSON.stringify(['city', 'culture', 'food', 'history']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 1600000,
    rating: 4.5,
    bestSeason: '10월-5월',
    pros: JSON.stringify(['저렴함', '타코 천국', '아즈텍 문화', '박물관 풍부']),
    cons: JSON.stringify(['치안 주의', '고산병 가능', '영어 안 통함']),
    description: '아즈텍과 스페인이 공존하는 대도시',
    highlights: JSON.stringify(['테오티와칸', '소칼로 광장', '프리다 칼로 박물관', '차풀테펙 공원']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 150000, mustDo: ['테오티와칸 피라미드', '소칼로 광장', '타코 투어'] })
  },
  {
    id: 'brazil-riodejaneiro',
    name: '리우데자네이루',
    country: '브라질',
    flag: '🇧🇷',
    styles: JSON.stringify(['beach', 'city', 'culture', 'adventure']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends']),
    flightTime: 'long',
    avgCost: 2200000,
    rating: 4.6,
    bestSeason: '12월-3월',
    pros: JSON.stringify(['코파카바나 해변', '예수상', '카니발', '삼바', '열정적인 분위기']),
    cons: JSON.stringify(['치안 매우 주의', '비행시간 매우 긺', '포르투갈어만', '빈부격차']),
    description: '열정의 도시, 카니발과 삼바의 본고장',
    highlights: JSON.stringify(['코르코바도 예수상', '슈가로프 산', '코파카바나 해변', '이파네마', '셀라론 계단']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 300000, mustDo: ['예수상 투어', '슈가로프 케이블카', '코파카바나 선셋'] })
  },
  {
    id: 'argentina-buenosaires',
    name: '부에노스아이레스',
    country: '아르헨티나',
    flag: '🇦🇷',
    styles: JSON.stringify(['city', 'culture', 'food']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 2300000,
    rating: 4.6,
    bestSeason: '10월-4월',
    pros: JSON.stringify(['탱고', '와인', '스테이크', '유럽 분위기', '열정적']),
    cons: JSON.stringify(['비행시간 매우 긺', '스페인어만', '인플레이션']),
    description: '남미의 파리, 탱고와 와인의 도시',
    highlights: JSON.stringify(['보카 지구', '레콜레타 묘지', '탱고쇼', '팔레르모', '플로리다 거리']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 250000, mustDo: ['탱고쇼', '보카 지구', '스테이크 맛집'] })
  },
  {
    id: 'peru-cusco',
    name: '쿠스코',
    country: '페루',
    flag: '🇵🇪',
    styles: JSON.stringify(['culture', 'history', 'adventure', 'nature']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 2000000,
    rating: 4.8,
    bestSeason: '5월-9월',
    pros: JSON.stringify(['마추픽추', '잉카 문명', '저렴함', '알파카', '독특한 문화']),
    cons: JSON.stringify(['고산병 주의', '영어 안 통함', '비행시간 긺']),
    description: '잉카 제국의 수도, 마추픽추의 관문',
    highlights: JSON.stringify(['마추픽추', '무지개 산', '사크사이와만', '우루밤바 계곡']),
    sampleItinerary: JSON.stringify({ days: 6, perDayCost: 200000, mustDo: ['마추픽추 트레킹', '무지개산 투어', '쿠스코 시내'] })
  },
  {
    id: 'chile-santiago',
    name: '산티아고',
    country: '칠레',
    flag: '🇨🇱',
    styles: JSON.stringify(['city', 'culture', 'nature', 'food']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 2200000,
    rating: 4.5,
    bestSeason: '10월-4월',
    pros: JSON.stringify(['와인', '안데스 산맥', '깨끗함', '치안 좋음', '해산물']),
    cons: JSON.stringify(['비행시간 매우 긺', '스페인어만']),
    description: '안데스 산맥 아래의 현대 도시, 와인의 천국',
    highlights: JSON.stringify(['산크리스토발 언덕', '발파라이소', '와이너리 투어', '중앙시장']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 250000, mustDo: ['와이너리 투어', '발파라이소 당일치기', '산크리스토발 언덕'] })
  },
  {
    id: 'cuba-havana',
    name: '아바나',
    country: '쿠바',
    flag: '🇨🇺',
    styles: JSON.stringify(['culture', 'city', 'history', 'beach']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 1900000,
    rating: 4.6,
    bestSeason: '11월-4월',
    pros: JSON.stringify(['1950년대 클래식카', '시가', '살사', '타임슬립 느낌', '저렴함']),
    cons: JSON.stringify(['인터넷 안 됨', '인프라 부족', '영어 안 통함', '비행 어려움']),
    description: '시간이 멈춘 도시, 클래식카와 시가의 나라',
    highlights: JSON.stringify(['말레콘 해변', '구시가지', '클래식카 투어', '모히토 바', '트리니다드']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 200000, mustDo: ['클래식카 투어', '모히토 바', '트리니다드 당일치기'] })
  },
  {
    id: 'colombia-cartagena',
    name: '카르타헤나',
    country: '콜롬비아',
    flag: '🇨🇴',
    styles: JSON.stringify(['beach', 'culture', 'city', 'history']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends']),
    flightTime: 'long',
    avgCost: 1800000,
    rating: 4.7,
    bestSeason: '12월-4월',
    pros: JSON.stringify(['카리브해 해변', '식민지 건축', '저렴함', '커피', '친절함']),
    cons: JSON.stringify(['치안 주의', '더움', '영어 안 통함']),
    description: '카리브해의 보석, 식민지 요새 도시',
    highlights: JSON.stringify(['구시가지 성벽', '로사리오 제도', '산펠리페 요새', '헤타세마니 광장']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 200000, mustDo: ['구시가지 산책', '로사리오 제도 투어', '커피 투어'] })
  },

  // ========================================
  // 오세아니아 (10개)
  // ========================================
  {
    id: 'australia-sydney',
    name: '시드니',
    country: '호주',
    flag: '🇦🇺',
    styles: JSON.stringify(['city', 'beach', 'culture', 'nature']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'family', 'friends']),
    flightTime: 'long',
    avgCost: 2200000,
    rating: 4.7,
    bestSeason: '9월-11월, 3월-5월',
    pros: JSON.stringify(['오페라하우스', '깨끗한 해변', '다문화', '안전함', '영어 통함']),
    cons: JSON.stringify(['비쌈', '비행시간 긺', '시차 큼']),
    description: '남반구의 보석, 오페라하우스와 하버 브릿지',
    highlights: JSON.stringify(['오페라하우스', '하버 브릿지', '본다이 비치', '달링 하버', '블루마운틴']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 400000, mustDo: ['오페라하우스 투어', '본다이 비치', '블루마운틴 투어'] })
  },
  {
    id: 'australia-melbourne',
    name: '멜버른',
    country: '호주',
    flag: '🇦🇺',
    styles: JSON.stringify(['city', 'culture', 'food', 'nature']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 2100000,
    rating: 4.6,
    bestSeason: '10월-4월',
    pros: JSON.stringify(['예술/문화', '카페 문화', '그레이트 오션 로드', '스포츠', '깨끗함']),
    cons: JSON.stringify(['비쌈', '날씨 변덕', '비행시간 긺']),
    description: '문화의 도시, 카페와 스트리트 아트의 천국',
    highlights: JSON.stringify(['그레이트 오션 로드', '플린더스 거리 역', '페더레이션 광장', '세인트 킬다', '유레카 스카이덱']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 400000, mustDo: ['그레이트 오션 로드 투어', '카페 호핑', '펭귄 퍼레이드'] })
  },
  {
    id: 'australia-goldcoast',
    name: '골드코스트',
    country: '호주',
    flag: '🇦🇺',
    styles: JSON.stringify(['beach', 'adventure', 'family', 'relaxation']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['family', 'couple', 'friends']),
    flightTime: 'long',
    avgCost: 1900000,
    rating: 4.6,
    bestSeason: '12월-2월',
    pros: JSON.stringify(['서핑 천국', '테마파크', '해변', '날씨 좋음', '한인 많음']),
    cons: JSON.stringify(['비쌈', '비행시간 긺']),
    description: '서핑과 테마파크의 천국, 끝없는 해변',
    highlights: JSON.stringify(['서퍼스 파라다이스', '무비월드', '드림월드', '바이런 베이', 'Q1 타워']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 350000, mustDo: ['서핑 레슨', '테마파크', '바이런베이 투어'] })
  },
  {
    id: 'newzealand-queenstown',
    name: '퀸스타운',
    country: '뉴질랜드',
    flag: '🇳🇿',
    styles: JSON.stringify(['nature', 'adventure', 'relaxation']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'long',
    avgCost: 2300000,
    rating: 4.9,
    bestSeason: '12월-2월, 6월-8월(스키)',
    pros: JSON.stringify(['절경', '번지점프 원조', '밀포드 사운드', '스키', '깨끗함']),
    cons: JSON.stringify(['비쌈', '비행시간 긺', '겨울 춥고 어두움']),
    description: '모험의 수도, 알프스와 호수가 만나는 천국',
    highlights: JSON.stringify(['밀포드 사운드', '스카이라인 곤돌라', '번지점프', '와카티푸 호수', '글레노키']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 450000, mustDo: ['밀포드 사운드 크루즈', '번지점프', '곤돌라+루지'] })
  },
  {
    id: 'newzealand-auckland',
    name: '오클랜드',
    country: '뉴질랜드',
    flag: '🇳🇿',
    styles: JSON.stringify(['city', 'nature', 'culture']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'family', 'friends']),
    flightTime: 'long',
    avgCost: 2000000,
    rating: 4.5,
    bestSeason: '12월-3월',
    pros: JSON.stringify(['깨끗함', '안전함', '항구 도시', '와이너리', '영어 통함']),
    cons: JSON.stringify(['비쌈', '비행시간 긺']),
    description: '항구의 도시, 호빗 마을의 관문',
    highlights: JSON.stringify(['스카이 타워', '와이헤키 섬', '호빗 마을', '데번포트', '미션 베이']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 400000, mustDo: ['호빗 마을 투어', '와이헤키 와이너리', '스카이타워 번지'] })
  },
  {
    id: 'guam-main',
    name: '괌',
    country: '괌',
    flag: '🇬🇺',
    styles: JSON.stringify(['beach', 'relaxation', 'shopping', 'family']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['family', 'couple', 'friends']),
    flightTime: 'medium',
    avgCost: 1000000,
    rating: 4.4,
    bestSeason: '12월-5월',
    pros: JSON.stringify(['가까움', '면세 쇼핑', '한국어 통함', '깨끗한 바다', '가족 친화']),
    cons: JSON.stringify(['볼거리 적음', '태풍 시즌', '물가 비쌈']),
    description: '가까운 휴양지, 면세 쇼핑과 해양 스포츠',
    highlights: JSON.stringify(['투몬 비치', '사랑의 절벽', '아가나 쇼핑센터', '스노클링', 'DFS']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 200000, mustDo: ['투몬비치 선셋', '스노클링', '면세점 쇼핑'] })
  },
  {
    id: 'saipan-main',
    name: '사이판',
    country: '사이판',
    flag: '🇲🇵',
    styles: JSON.stringify(['beach', 'relaxation', 'adventure', 'family']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['family', 'couple']),
    flightTime: 'medium',
    avgCost: 1100000,
    rating: 4.5,
    bestSeason: '12월-6월',
    pros: JSON.stringify(['가까움', '깨끗한 바다', '한국어 통함', '다이빙 명소', '조용함']),
    cons: JSON.stringify(['태풍 시즌 주의', '물가 비쌈', '볼거리 적음']),
    description: '북마리아나의 진주, 다이빙과 스노클링 천국',
    highlights: JSON.stringify(['마나가하 섬', '그로토', '만세 절벽', '타포차우 산', '마이크로 비치']),
    sampleItinerary: JSON.stringify({ days: 4, perDayCost: 220000, mustDo: ['그로토 다이빙', '마나가하 섬', '스노클링'] })
  },
  {
    id: 'fiji-main',
    name: '피지',
    country: '피지',
    flag: '🇫🇯',
    styles: JSON.stringify(['beach', 'relaxation', 'nature', 'adventure']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'family']),
    flightTime: 'long',
    avgCost: 2400000,
    rating: 4.8,
    bestSeason: '5월-10월',
    pros: JSON.stringify(['천국 같은 바다', '프렌들리', '스노클링/다이빙', '리조트', '영어 통함']),
    cons: JSON.stringify(['비행시간 긺', '비쌈', '인프라 부족']),
    description: '남태평양의 천국, 행복지수 1위의 나라',
    highlights: JSON.stringify(['야사와 제도', '블루라군', '산호초', '클라우드 9', '전통 마을 투어']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 400000, mustDo: ['야사와 제도 투어', '블루라군 스노클링', '전통 공연'] })
  },
  {
    id: 'tahiti-main',
    name: '타히티',
    country: '프랑스령 폴리네시아',
    flag: '🇵🇫',
    styles: JSON.stringify(['beach', 'relaxation', 'nature']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple']),
    flightTime: 'long',
    avgCost: 4000000,
    rating: 4.9,
    bestSeason: '5월-10월',
    pros: JSON.stringify(['천국 중의 천국', '보라보라', '수상 방갈로', '프렌치 폴리네시안', '절대 평화']),
    cons: JSON.stringify(['매우 비쌈', '비행시간 매우 긺', '할 일 없음']),
    description: '남태평양의 낙원, 보라보라의 에메랄드 라군',
    highlights: JSON.stringify(['보라보라 섬', '무레아 섬', '수상 방갈로', '라군 투어', '폴리네시안 춤']),
    sampleItinerary: JSON.stringify({ days: 7, perDayCost: 800000, mustDo: ['보라보라 수상방갈로', '라군 스노클링', '선셋 크루즈'] })
  },

  // ========================================
  // 아프리카 (10개)
  // ========================================
  {
    id: 'egypt-cairo',
    name: '카이로',
    country: '이집트',
    flag: '🇪🇬',
    styles: JSON.stringify(['culture', 'history', 'city']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'long',
    avgCost: 1500000,
    rating: 4.6,
    bestSeason: '10월-4월',
    pros: JSON.stringify(['피라미드', '파라오 문명', '저렴함', '나일강 크루즈', '스핑크스']),
    cons: JSON.stringify(['더움', '바가지 많음', '위생 주의', '치안 주의']),
    description: '파라오의 나라, 피라미드와 나일강',
    highlights: JSON.stringify(['기자 피라미드', '스핑크스', '이집트 박물관', '나일강 크루즈', '룩소르']),
    sampleItinerary: JSON.stringify({ days: 6, perDayCost: 150000, mustDo: ['피라미드 투어', '나일강 크루즈', '이집트 박물관'] })
  },
  {
    id: 'morocco-marrakech',
    name: '마라케시',
    country: '모로코',
    flag: '🇲🇦',
    styles: JSON.stringify(['culture', 'city', 'adventure', 'food']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 1600000,
    rating: 4.7,
    bestSeason: '3월-5월, 9월-11월',
    pros: JSON.stringify(['사하라 사막', '이슬람 문화', '메디나 시장', '저렴함', '독특한 건축']),
    cons: JSON.stringify(['바가지 주의', '더움', '영어 잘 안 통함']),
    description: '사하라의 관문, 천일야화의 도시',
    highlights: JSON.stringify(['사하라 사막 투어', '제마 엘프나 광장', '마조렐 정원', '메디나', '바히아 궁전']),
    sampleItinerary: JSON.stringify({ days: 5, perDayCost: 180000, mustDo: ['사하라 낙타 투어', '메디나 시장', '마조렐 정원'] })
  },
  {
    id: 'southafrica-capetown',
    name: '케이프타운',
    country: '남아프리카공화국',
    flag: '🇿🇦',
    styles: JSON.stringify(['nature', 'city', 'adventure', 'beach']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'long',
    avgCost: 2000000,
    rating: 4.8,
    bestSeason: '11월-3월',
    pros: JSON.stringify(['테이블 마운틴', '펭귄 해변', '와이너리', '희망봉', '영어 통함']),
    cons: JSON.stringify(['치안 주의', '비행시간 매우 긺', '시차 큼']),
    description: '아프리카의 진주, 두 대양이 만나는 곳',
    highlights: JSON.stringify(['테이블 마운틴', '희망봉', '펭귄 해변', '와인랜드', 'V&A 워터프론트']),
    sampleItinerary: JSON.stringify({ days: 6, perDayCost: 250000, mustDo: ['테이블 마운틴 등반', '펭귄 해변', '희망봉 투어'] })
  },
  {
    id: 'kenya-nairobi',
    name: '나이로비',
    country: '케냐',
    flag: '🇰🇪',
    styles: JSON.stringify(['nature', 'adventure', 'culture']),
    budgetRange: JSON.stringify(['medium', 'high']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'long',
    avgCost: 2500000,
    rating: 4.7,
    bestSeason: '7월-10월, 1월-2월',
    pros: JSON.stringify(['사파리', '빅5', '동물대이동', '마사이족', '킬리만자로 근처']),
    cons: JSON.stringify(['비쌈', '치안 주의', '비행시간 긺']),
    description: '사파리의 천국, 동물대이동의 현장',
    highlights: JSON.stringify(['마사이 마라', '나쿠루 호수', '암보셀리', '기린 센터', '코끼리 보호소']),
    sampleItinerary: JSON.stringify({ days: 7, perDayCost: 400000, mustDo: ['마사이마라 사파리', '동물대이동', '마사이족 마을'] })
  },
  {
    id: 'tanzania-serengeti',
    name: '세렝게티',
    country: '탄자니아',
    flag: '🇹🇿',
    styles: JSON.stringify(['nature', 'adventure']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'friends', 'family']),
    flightTime: 'long',
    avgCost: 3000000,
    rating: 4.9,
    bestSeason: '6월-10월',
    pros: JSON.stringify(['세계 최고 사파리', '동물대이동', '빅5', '원시 자연', '킬리만자로']),
    cons: JSON.stringify(['매우 비쌈', '비행 어려움', '기본 시설']),
    description: '아프리카의 심장, 야생의 왕국',
    highlights: JSON.stringify(['세렝게티 국립공원', '응고롱고로 분화구', '킬리만자로', '잔지바르']),
    sampleItinerary: JSON.stringify({ days: 8, perDayCost: 500000, mustDo: ['세렝게티 사파리', '응고롱고로 투어', '잔지바르 휴양'] })
  },
  {
    id: 'madagascar-main',
    name: '마다가스카르',
    country: '마다가스카르',
    flag: '🇲🇬',
    styles: JSON.stringify(['nature', 'adventure', 'beach']),
    budgetRange: JSON.stringify(['medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 2200000,
    rating: 4.6,
    bestSeason: '4월-11월',
    pros: JSON.stringify(['독특한 생태계', '여우원숭이', '바오밥 나무', '저렴함', '미개척지']),
    cons: JSON.stringify(['인프라 매우 부족', '프랑스어', '교통 불편']),
    description: '지구 최후의 비밀, 바오밥과 여우원숭이의 나라',
    highlights: JSON.stringify(['바오밥 나무 길', '치징이 국립공원', '노시베', '이살로 국립공원']),
    sampleItinerary: JSON.stringify({ days: 8, perDayCost: 200000, mustDo: ['바오밥 나무 선셋', '여우원숭이 투어', '노시베 해변'] })
  },
  {
    id: 'seychelles-main',
    name: '세이셸',
    country: '세이셸',
    flag: '🇸🇨',
    styles: JSON.stringify(['beach', 'relaxation', 'nature']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple']),
    flightTime: 'long',
    avgCost: 3500000,
    rating: 4.9,
    bestSeason: '4월-5월, 10월-11월',
    pros: JSON.stringify(['천국 같은 해변', '프라이빗 리조트', '거북이', '스노클링', '허니문 천국']),
    cons: JSON.stringify(['매우 비쌈', '비행 어려움', '할 일 없음']),
    description: '인도양의 에덴, 세계에서 가장 아름다운 해변',
    highlights: JSON.stringify(['앙스 소스 다르장', '라디그 섬', '거북이 보호소', '발레 드 메', '프랄린 섬']),
    sampleItinerary: JSON.stringify({ days: 7, perDayCost: 600000, mustDo: ['앙스 소스 다르장', '섬 호핑', '스노클링'] })
  },
  {
    id: 'mauritius-main',
    name: '모리셔스',
    country: '모리셔스',
    flag: '🇲🇺',
    styles: JSON.stringify(['beach', 'relaxation', 'nature', 'adventure']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'family']),
    flightTime: 'long',
    avgCost: 3000000,
    rating: 4.8,
    bestSeason: '5월-12월',
    pros: JSON.stringify(['에메랄드 바다', '올인클루시브', '돌고래', '7색 땅', '영어/프랑스어']),
    cons: JSON.stringify(['매우 비쌈', '비행시간 긺']),
    description: '인도양의 보석, 럭셔리 리조트의 천국',
    highlights: JSON.stringify(['7색 땅', '샤마렐 폭포', '일 오 세르프', '블랙 리버 협곡', '돌고래 투어']),
    sampleItinerary: JSON.stringify({ days: 6, perDayCost: 500000, mustDo: ['돌고래 투어', '7색 땅', '수중 폭포'] })
  },
  {
    id: 'tunisia-tunis',
    name: '튀니스',
    country: '튀니지',
    flag: '🇹🇳',
    styles: JSON.stringify(['culture', 'history', 'beach', 'adventure']),
    budgetRange: JSON.stringify(['low', 'medium']),
    bestFor: JSON.stringify(['couple', 'friends', 'solo']),
    flightTime: 'long',
    avgCost: 1400000,
    rating: 4.5,
    bestSeason: '3월-5월, 9월-11월',
    pros: JSON.stringify(['사하라 사막', '로마 유적', '지중해', '저렴함', '스타워즈 촬영지']),
    cons: JSON.stringify(['영어 안 통함', '치안 주의']),
    description: '지중해와 사하라, 로마 유적과 이슬람 문화',
    highlights: JSON.stringify(['카르타고 유적', '사하라 사막', '시디부사이드', '콜로세움', '스타워즈 세트']),
    sampleItinerary: JSON.stringify({ days: 6, perDayCost: 150000, mustDo: ['사하라 사막 투어', '카르타고 유적', '시디부사이드'] })
  },
  {
    id: 'botswana-okavango',
    name: '오카방고',
    country: '보츠와나',
    flag: '🇧🇼',
    styles: JSON.stringify(['nature', 'adventure']),
    budgetRange: JSON.stringify(['high']),
    bestFor: JSON.stringify(['couple', 'friends']),
    flightTime: 'long',
    avgCost: 3500000,
    rating: 4.9,
    bestSeason: '5월-10월',
    pros: JSON.stringify(['프리미엄 사파리', '빅5', '보케로', '모래사막', '야생 그대로']),
    cons: JSON.stringify(['매우 비쌈', '비행 어려움', '기본 시설']),
    description: '아프리카 최고급 사파리, 야생의 정수',
    highlights: JSON.stringify(['오카방고 델타', '초베 국립공원', '칼라하리 사막', '빅토리아 폭포(근처)']),
    sampleItinerary: JSON.stringify({ days: 8, perDayCost: 600000, mustDo: ['오카방고 보트 사파리', '초베 코끼리', '칼라하리 투어'] })
  }
];

module.exports = destinationsData;
